[2023-12-21T17:43:16.798-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:42:58.245265+00:00 [queued]>
[2023-12-21T17:43:16.801-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:42:58.245265+00:00 [queued]>
[2023-12-21T17:43:16.801-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-21T17:43:17.044-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonVirtualenvOperator): checks_ingest> on 2023-12-21 20:42:58.245265+00:00
[2023-12-21T17:43:17.048-0300] {standard_task_runner.py:60} INFO - Started process 128086 to run task
[2023-12-21T17:43:17.051-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'checks_ingest', 'manual__2023-12-21T20:42:58.245265+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmp_qwo_lwm']
[2023-12-21T17:43:17.052-0300] {standard_task_runner.py:88} INFO - Job 19: Subtask checks_ingest
[2023-12-21T17:43:17.207-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:42:58.245265+00:00 [running]> on host franco-MS-7B84
[2023-12-21T17:43:17.543-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='checks_ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T20:42:58.245265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T20:42:58.245265+00:00'
[2023-12-21T17:43:17.544-0300] {process_utils.py:182} INFO - Executing cmd: /home/franco/Documents/Projects/soda/.venv/bin/python -m virtualenv /tmp/venvm0v5ajtw --python=python
[2023-12-21T17:43:17.545-0300] {process_utils.py:186} INFO - Output:
[2023-12-21T17:43:17.558-0300] {process_utils.py:190} INFO - /home/franco/Documents/Projects/soda/.venv/bin/python: No module named virtualenv
[2023-12-21T17:43:17.560-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 711, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 623, in _prepare_venv
    prepare_virtualenv(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 104, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvm0v5ajtw', '--python=python']' returned non-zero exit status 1.
[2023-12-21T17:43:17.564-0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=model_adventureworks_sales_category, task_id=checks_ingest, execution_date=20231221T204258, start_date=20231221T204316, end_date=20231221T204317
[2023-12-21T17:43:17.836-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task checks_ingest (Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvm0v5ajtw', '--python=python']' returned non-zero exit status 1.; 128086)
[2023-12-21T17:43:17.863-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-21T17:43:17.877-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
