[2023-12-21T17:20:21.231-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.dbt_transform manual__2023-12-21T20:20:03.209915+00:00 [queued]>
[2023-12-21T17:20:21.235-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.dbt_transform manual__2023-12-21T20:20:03.209915+00:00 [queued]>
[2023-12-21T17:20:21.236-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-21T17:20:21.414-0300] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): dbt_transform> on 2023-12-21 20:20:03.209915+00:00
[2023-12-21T17:20:21.421-0300] {standard_task_runner.py:60} INFO - Started process 119761 to run task
[2023-12-21T17:20:21.424-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'dbt_transform', 'manual__2023-12-21T20:20:03.209915+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmpdm1fs7o2']
[2023-12-21T17:20:21.425-0300] {standard_task_runner.py:88} INFO - Job 12: Subtask dbt_transform
[2023-12-21T17:20:21.605-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.dbt_transform manual__2023-12-21T20:20:03.209915+00:00 [running]> on host franco-MS-7B84
[2023-12-21T17:20:21.948-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='dbt_transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T20:20:03.209915+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T20:20:03.209915+00:00'
[2023-12-21T17:20:21.949-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T17:20:21.950-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /home/franco/Documents/Projects/soda/dbt/dbt_models/models/dbt --select transform']
[2023-12-21T17:20:21.964-0300] {subprocess.py:86} INFO - Output:
[2023-12-21T17:20:23.658-0300] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2023-12-21T17:20:23.659-0300] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2023-12-21T17:20:23.659-0300] {subprocess.py:93} INFO - 
[2023-12-21T17:20:23.659-0300] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/home/franco/Documents/Projects/soda/dbt/dbt_models/models/dbt' does not exist.
[2023-12-21T17:20:23.906-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-21T17:20:23.915-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-21T17:20:23.919-0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=model_adventureworks_sales_category, task_id=dbt_transform, execution_date=20231221T202003, start_date=20231221T202021, end_date=20231221T202023
[2023-12-21T17:20:24.215-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task dbt_transform (Bash command failed. The command returned a non-zero exit code 2.; 119761)
[2023-12-21T17:20:24.243-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-21T17:20:24.265-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
