[2023-12-21T11:43:36.834-0300] {processor.py:161} INFO - Started process (PID=43931) to work on /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:43:36.834-0300] {processor.py:830} INFO - Processing file /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py for tasks to queue
[2023-12-21T11:43:36.835-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:43:36.835-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:43:43.286-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:43:43.281-0300] {dagbag.py:348} ERROR - Failed to import: /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py", line 51, in <module>
    section_2 = SubDagOperator(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/subdag.py", line 97, in __init__
    self._validate_pool(session)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/subdag.py", line 122, in _validate_pool
    pool = session.scalar(select(Pool).where(Pool.slots == 1, Pool.pool == self.pool))
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT slot_pool.id, slot_pool.pool, slot_pool.slots, slot_pool.description, slot_pool.include_deferred 
FROM slot_pool 
WHERE slot_pool.slots = ? AND slot_pool.pool = ?]
[parameters: (1, 'default_pool')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-12-21T11:43:43.286-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:43:52.757-0300] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/dag_processing/processor.py", line 641, in update_import_errors
    session.query(DagModel)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3306, in update
    result = self.session.execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE dag SET has_import_errors=? WHERE dag.fileloc = ?]
[parameters: (1, '/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-12-21T11:45:56.468-0300] {processor.py:161} INFO - Started process (PID=44744) to work on /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:45:56.480-0300] {processor.py:830} INFO - Processing file /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py for tasks to queue
[2023-12-21T11:45:56.480-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:56.480-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:45:56.492-0300] {processor.py:840} INFO - DAG(s) 'example_subdag_operator.section-1', 'example_subdag_operator.section-2', 'example_subdag_operator' retrieved from /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py
[2023-12-21T11:45:56.778-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:56.778-0300] {override.py:1769} INFO - Created Permission View: can read on DAG:example_subdag_operator
[2023-12-21T11:45:56.926-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:56.926-0300] {override.py:1769} INFO - Created Permission View: can delete on DAG:example_subdag_operator
[2023-12-21T11:45:57.143-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.142-0300] {override.py:1769} INFO - Created Permission View: can edit on DAG:example_subdag_operator
[2023-12-21T11:45:57.143-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.143-0300] {dag.py:3033} INFO - Sync 3 DAGs
[2023-12-21T11:45:57.154-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.154-0300] {dag.py:3055} INFO - Creating ORM DAG for example_subdag_operator
[2023-12-21T11:45:57.154-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.154-0300] {dag.py:3055} INFO - Creating ORM DAG for example_subdag_operator.section-1
[2023-12-21T11:45:57.155-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.155-0300] {dag.py:3055} INFO - Creating ORM DAG for example_subdag_operator.section-2
[2023-12-21T11:45:57.164-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.164-0300] {dag.py:3820} INFO - Setting next_dagrun for example_subdag_operator to 2022-01-01T00:00:00+00:00, run_after=2022-01-01T00:00:00+00:00
[2023-12-21T11:45:57.165-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.165-0300] {dag.py:3820} INFO - Setting next_dagrun for example_subdag_operator.section-1 to None, run_after=None
[2023-12-21T11:45:57.165-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.165-0300] {dag.py:3820} INFO - Setting next_dagrun for example_subdag_operator.section-2 to None, run_after=None
[2023-12-21T11:45:57.171-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.171-0300] {dag.py:3033} INFO - Sync 2 DAGs
[2023-12-21T11:45:57.175-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.175-0300] {dag.py:3820} INFO - Setting next_dagrun for example_subdag_operator.section-1 to None, run_after=None
[2023-12-21T11:45:57.177-0300] {logging_mixin.py:188} INFO - [2023-12-21T11:45:57.177-0300] {dag.py:3820} INFO - Setting next_dagrun for example_subdag_operator.section-2 to None, run_after=None
[2023-12-21T11:45:57.536-0300] {processor.py:183} INFO - Processing /home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/example_dags/example_subdag_operator.py took 1.071 seconds
