[2023-12-21T14:56:55.143-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T14:56:55.146-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T14:56:55.146-0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-21T14:56:55.318-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonVirtualenvOperator): checks_ingest> on 2023-12-20 00:00:00+00:00
[2023-12-21T14:56:55.324-0300] {standard_task_runner.py:60} INFO - Started process 88621 to run task
[2023-12-21T14:56:55.327-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'checks_ingest', 'scheduled__2023-12-20T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmploog5bs4']
[2023-12-21T14:56:55.328-0300] {standard_task_runner.py:88} INFO - Job 8: Subtask checks_ingest
[2023-12-21T14:56:55.496-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.checks_ingest scheduled__2023-12-20T00:00:00+00:00 [running]> on host franco-MS-7B84
[2023-12-21T14:56:55.976-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='checks_ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-20T00:00:00+00:00'
[2023-12-21T14:56:55.977-0300] {process_utils.py:182} INFO - Executing cmd: /home/franco/Documents/Projects/soda/.venv/bin/python -m virtualenv /tmp/venvdzyyjffq --python=python
[2023-12-21T14:56:55.978-0300] {process_utils.py:186} INFO - Output:
[2023-12-21T14:56:55.991-0300] {process_utils.py:190} INFO - /home/franco/Documents/Projects/soda/.venv/bin/python: No module named virtualenv
[2023-12-21T14:56:55.993-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 711, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 623, in _prepare_venv
    prepare_virtualenv(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 104, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvdzyyjffq', '--python=python']' returned non-zero exit status 1.
[2023-12-21T14:56:55.998-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=model_adventureworks_sales_category, task_id=checks_ingest, execution_date=20231220T000000, start_date=20231221T175655, end_date=20231221T175655
[2023-12-21T14:56:56.192-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task checks_ingest (Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvdzyyjffq', '--python=python']' returned non-zero exit status 1.; 88621)
[2023-12-21T14:56:56.220-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-21T14:56:56.241-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
