[2023-12-21T17:34:37.967-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:20:03.209915+00:00 [queued]>
[2023-12-21T17:34:37.970-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:20:03.209915+00:00 [queued]>
[2023-12-21T17:34:37.970-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-21T17:34:38.130-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonVirtualenvOperator): checks_ingest> on 2023-12-21 20:20:03.209915+00:00
[2023-12-21T17:34:38.136-0300] {standard_task_runner.py:60} INFO - Started process 124687 to run task
[2023-12-21T17:34:38.139-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'checks_ingest', 'manual__2023-12-21T20:20:03.209915+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmpzhqfi2hv']
[2023-12-21T17:34:38.141-0300] {standard_task_runner.py:88} INFO - Job 13: Subtask checks_ingest
[2023-12-21T17:34:38.462-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:20:03.209915+00:00 [running]> on host franco-MS-7B84
[2023-12-21T17:34:38.822-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='checks_ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T20:20:03.209915+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T20:20:03.209915+00:00'
[2023-12-21T17:34:38.823-0300] {process_utils.py:182} INFO - Executing cmd: /home/franco/Documents/Projects/soda/.venv/bin/python -m virtualenv /tmp/venvc2tp7h95 --python=python
[2023-12-21T17:34:38.823-0300] {process_utils.py:186} INFO - Output:
[2023-12-21T17:34:38.836-0300] {process_utils.py:190} INFO - /home/franco/Documents/Projects/soda/.venv/bin/python: No module named virtualenv
[2023-12-21T17:34:38.839-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 711, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 623, in _prepare_venv
    prepare_virtualenv(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 104, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvc2tp7h95', '--python=python']' returned non-zero exit status 1.
[2023-12-21T17:34:38.844-0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=model_adventureworks_sales_category, task_id=checks_ingest, execution_date=20231221T202003, start_date=20231221T203437, end_date=20231221T203438
[2023-12-21T17:34:39.023-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task checks_ingest (Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venvc2tp7h95', '--python=python']' returned non-zero exit status 1.; 124687)
[2023-12-21T17:34:39.034-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-21T17:34:39.047-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
