[2023-12-21T17:42:37.952-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:16:01.069761+00:00 [queued]>
[2023-12-21T17:42:37.959-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:16:01.069761+00:00 [queued]>
[2023-12-21T17:42:37.959-0300] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-21T17:42:38.109-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonVirtualenvOperator): checks_ingest> on 2023-12-21 20:16:01.069761+00:00
[2023-12-21T17:42:38.116-0300] {standard_task_runner.py:60} INFO - Started process 127887 to run task
[2023-12-21T17:42:38.119-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'checks_ingest', 'manual__2023-12-21T20:16:01.069761+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmpx3u8ftot']
[2023-12-21T17:42:38.121-0300] {standard_task_runner.py:88} INFO - Job 17: Subtask checks_ingest
[2023-12-21T17:42:38.310-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-21T20:16:01.069761+00:00 [running]> on host franco-MS-7B84
[2023-12-21T17:42:38.588-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='checks_ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T20:16:01.069761+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T20:16:01.069761+00:00'
[2023-12-21T17:42:38.589-0300] {process_utils.py:182} INFO - Executing cmd: /home/franco/Documents/Projects/soda/.venv/bin/python -m virtualenv /tmp/venv2xacju3j --python=python
[2023-12-21T17:42:38.590-0300] {process_utils.py:186} INFO - Output:
[2023-12-21T17:42:38.604-0300] {process_utils.py:190} INFO - /home/franco/Documents/Projects/soda/.venv/bin/python: No module named virtualenv
[2023-12-21T17:42:38.606-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 711, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 623, in _prepare_venv
    prepare_virtualenv(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 104, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venv2xacju3j', '--python=python']' returned non-zero exit status 1.
[2023-12-21T17:42:38.611-0300] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=model_adventureworks_sales_category, task_id=checks_ingest, execution_date=20231221T201601, start_date=20231221T204237, end_date=20231221T204238
[2023-12-21T17:42:38.766-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task checks_ingest (Command '['/home/franco/Documents/Projects/soda/.venv/bin/python', '-m', 'virtualenv', '/tmp/venv2xacju3j', '--python=python']' returned non-zero exit status 1.; 127887)
[2023-12-21T17:42:38.812-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-21T17:42:38.832-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
