[2023-12-22T14:07:31.311-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-22T17:07:22.167736+00:00 [queued]>
[2023-12-22T14:07:31.320-0300] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-22T17:07:22.167736+00:00 [queued]>
[2023-12-22T14:07:31.320-0300] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-22T14:07:31.496-0300] {taskinstance.py:2192} INFO - Executing <Task(PythonVirtualenvOperator): checks_ingest> on 2023-12-22 17:07:22.167736+00:00
[2023-12-22T14:07:31.502-0300] {standard_task_runner.py:60} INFO - Started process 81925 to run task
[2023-12-22T14:07:31.505-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'model_adventureworks_sales_category', 'checks_ingest', 'manual__2023-12-22T17:07:22.167736+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/model_sales_category.py', '--cfg-path', '/tmp/tmp0vnc7rna']
[2023-12-22T14:07:31.506-0300] {standard_task_runner.py:88} INFO - Job 35: Subtask checks_ingest
[2023-12-22T14:07:31.646-0300] {task_command.py:423} INFO - Running <TaskInstance: model_adventureworks_sales_category.checks_ingest manual__2023-12-22T17:07:22.167736+00:00 [running]> on host franco-MS-7B84
[2023-12-22T14:07:31.946-0300] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='soda_core' AIRFLOW_CTX_DAG_ID='model_adventureworks_sales_category' AIRFLOW_CTX_TASK_ID='checks_ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T17:07:22.167736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T17:07:22.167736+00:00'
[2023-12-22T14:07:31.947-0300] {process_utils.py:182} INFO - Executing cmd: /home/franco/Documents/Projects/soda/.venv/bin/python -m virtualenv /tmp/venv7ioh_js0 --python=python
[2023-12-22T14:07:31.948-0300] {process_utils.py:186} INFO - Output:
[2023-12-22T14:07:37.239-0300] {process_utils.py:190} INFO - created virtual environment CPython3.10.12.final.0-64 in 5220ms
[2023-12-22T14:07:37.239-0300] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv7ioh_js0, clear=False, no_vcs_ignore=False, global=False)
[2023-12-22T14:07:37.239-0300] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/franco/.local/share/virtualenv)
[2023-12-22T14:07:37.239-0300] {process_utils.py:190} INFO -     added seed packages: pip==23.3.2, setuptools==69.0.2, wheel==0.42.0
[2023-12-22T14:07:37.239-0300] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-12-22T14:07:37.251-0300] {process_utils.py:182} INFO - Executing cmd: /tmp/venv7ioh_js0/bin/pip install -r /tmp/venv7ioh_js0/requirements.txt
[2023-12-22T14:07:37.264-0300] {process_utils.py:186} INFO - Output:
[2023-12-22T14:07:38.492-0300] {process_utils.py:190} INFO - ERROR: Could not find a version that satisfies the requirement soda-postgres (from versions: none)
[2023-12-22T14:07:38.492-0300] {process_utils.py:190} INFO - ERROR: No matching distribution found for soda-postgres
[2023-12-22T14:07:39.588-0300] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 711, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 623, in _prepare_venv
    prepare_virtualenv(
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 118, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/franco/Documents/Projects/soda/.venv/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv7ioh_js0/bin/pip', 'install', '-r', '/tmp/venv7ioh_js0/requirements.txt']' returned non-zero exit status 1.
[2023-12-22T14:07:40.923-0300] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=model_adventureworks_sales_category, task_id=checks_ingest, execution_date=20231222T170722, start_date=20231222T170731, end_date=20231222T170740
[2023-12-22T14:07:41.107-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task checks_ingest (Command '['/tmp/venv7ioh_js0/bin/pip', 'install', '-r', '/tmp/venv7ioh_js0/requirements.txt']' returned non-zero exit status 1.; 81925)
[2023-12-22T14:07:43.438-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-22T14:07:43.455-0300] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
